//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public int id { get; set; }
        public string nombres { get; set; }
        public string apellidos { get; set; }
        public string numero_identificacion { get; set; }
        public string email { get; set; }
        public string telefono { get; set; }
        public string tipo_identificacion { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public string concat_identificacion_tipo { get; set; }
        public string concat_nombre_apellido { get; set; }
    }
}
